name: Sample workflow for Firebase Distribution action
on: [push]
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 
        uses: actions/checkout@master
      - name: Get sample .apk for test purposes
        run: wget https://github.com/appium/appium/raw/master/sample-code/apps/ApiDemos-debug.apk
      - name: Upload artifact to Firebase Distribution
        uses: ./
        with:
          appId: ${{secrets.FIREBASE_APP_ID}} 
          token: ${{secrets.FIREBASE_TOKEN}} 
          groups: Testers 
          file: ApiDemos-debug.apk
      - name: Upload artifact to Firebase Distribution with debug
        uses: ./
        with:
          appId: ${{secrets.FIREBASE_APP_ID}}
          token: ${{secrets.FIREBASE_TOKEN}}
          groups: Testers
          file: ApiDemos-debug.apk
          debug: true

 
